### PR TITLE
Added logPurchase support

### PR DESCRIPTION
**Pull request by Protossoario**
Allows users to log purchases through the Facebook SDK specifying the currency

### CODE REVIEW

**Comment by ashcoding** [comment]
@Protossoario Thanks for the PR. Before we could review this, could you sign the CLA?
https://cla.appcelerator.com/

**Comment by ashcoding** [comment]
Also, could you undo/remove the file change of android/build.properties.example → android/build.properties. Thank you!

**Comment by Protossoario** [comment]
I successfully removed the change of build.properties.example and signed the CLA!

**Comment by ashcoding** [comment]
@Protossoario sorry to bother you again. The auto check didn't show your github account as signed. Did you sign it here https://cla.appcelerator.com/ or another location?

Also, could you rebase/merge all the commits into one? Seems like some other commit history came along with it after you removed that file. If you could do this on this branch http://makandracards.com/makandra/527-squash-several-git-commits-into-a-single-commit (Easy mode: Reset your feature branch to the master state) and then force push the updated branch, that would be awesome! 

Sorry for the request! And thanks again!

**Comment by Protossoario** [comment]
Thanks for the link! It was really easy to do the reset with the instructions on that page and the pull request should be a lot cleaner now.

As for the CLA, I can't seem to sign it. I try clicking the "Sign in with GitHub" button, but it keeps redirecting me to the same page over and over.

**Comment by ashcoding** [comment]
@Protossoario thanks! With regards to the CLA, could you try again? Perhaps it's something to do with your Github settings...

**Comment by Protossoario** [comment]
Finally! It seems there was an issue with Chrome which was preventing me from signing the CLA. I tried with Safari and it finally worked just fine.

**Comment by hansemannn** [comment]
@ashcoding Can we tackle this one? We will also need docs updates here, would be great if @Protossoario could provide them! :-)

**Comment by ashcoding** [comment]
@hansemannn Yup. This is okay.

**Comment by hansemannn** [comment]
@Protossoario Any update here? Has been some more months now. As the code currently also has merge problems, please also rebase your PR to ensure the continuous integration. Also think of the docs. Thank you!

**Comment by hansemannn** [comment]
Finally resolved all merge conflicts, added the iOS implementation, docs, JIRA-ticket and example. Closing in favor of: https://github.com/appcelerator-modules/ti.facebook/pull/49

**Pull request closed without merging**
