### PR TITLE
[TIMOB-15339] Merge Request for FB Modules for Android and iOS

### PR DESCRIPTION
**Pull request by ashcoding**

### CODE REVIEW

**Comment by pec1985** [comment]
@ashcoding we need to remove any binaries, binaries that we generate, from the PR, we should not check in any *.so, *.zip, etc.. unless if a third party dependency

**Comment by pec1985** [comment]
@ashcoding for android, remove the `build.properties` file and just leave the `build.properties.example`
For the `build.properties.example`, the properties need to be generic, like...[this one](https://github.com/appcelerator-modules/ti.paint/blob/master/android/build.properties.example) where the paths are not hard-coded to the developer's machine

**Comment by pec1985** [comment]
The iOS version has hard-coded paths in the Xcode project, remove them here:
screen shot 2015-03-03 at 10 31 43 am

**Comment by pec1985** [comment]
The Android version requires Ti SDK 4.0.0, but the iOS version requires 3.5.0.GA - Both should require the same version

**Comment by ashcoding** [comment]
@pec1985 Thank you for letting me know about those things that I need to do. Especially with that picture. Thanks!

**Comment by ashcoding** [comment]
@pec1985  The Docs will be updated in another PR after this. Please review for the changes that you mentioned. Thank you!

**Comment by pec1985** [comment]
**APPROVED!**

**Pull request merged**
