### PR TITLE
feat: update sdk's to 4.39.0

### PR DESCRIPTION
**Pull request by hansemannn**
Updates both the iOS and Android Facebook SDK to 4.39.0 (latest). Also removes the deprecated `LikeButton` API that did not work since a while anyway. Facebook removed it's functionality last year already, so ripping it out will align with the latest Facebook SDK.

[facebook-android-8.0.0.zip](https://github.com/appcelerator-modules/ti.facebook/files/2849430/facebook-android-8.0.0.zip)
[facebook-iphone-6.0.0.zip](https://www.dropbox.com/s/0mic30p5zlzf7io/facebook-iphone-6.0.0.zip?dl=1)

### CODE REVIEW

**Comment by hansemannn** [comment]
@vijaysingh-axway @janvennemann Can someone review this? It's a pretty important update and brings Appc to the latest versions of the SDK. Thanks!

**Comment by antonioduran** [comment]
Hello @hansemannn . Good afternoon. 

The modules you attached in your first comment:

> facebook-android-8.0.0.zip
> facebook-iphone-6.0.0.zip

They have the latest SDK version of facebook right?

**Comment by hansemannn** [comment]
I think I updated them one more time. Please build it from the source to be sure.

**Comment by jkotchoff** [comment]
+1 for someone to review this please. Facebook's dashboard is requiring us to update to v.4.39.0 and it contains a crucial feature for us (automatic verification of in-app purchases).

**Comment by hansemannn** [comment]
@jkotchoff I updated the attached binaries to the latest locally built version. We use it in production already.

**Comment by janvennemann** [comment]
@hansemannn can you update the [Jenkinsfile](../blob/master/Jenkinsfile) to build with a recent SDK so Jenkins passes? Thanks!

**Comment by hansemannn** [comment]
Done! I hope it builds successfully. *EDIT*: Nope, doesn't work.

**Comment by janvennemann** [comment]
Oh well, guess i'll have to take a look tomorrow.

**Comment by antonioduran** [comment]
Hello @hansemannn 
CC: @janvennemann @jkotchoff 

Not sure whether I am doing something wrong, but even with these versions of the modules compiled:

> facebook-android-8.0.0.zip
> facebook-iphone-6.0.0.zip

I am getting the issue about:
`{"success":false,"code":308,"cancelled":false,"error":"Error 308 detected: Please enable keychain-sharing in your projectby creating an Entitlements file. For more information check the\"Migrate to iOS 10\" section in https://docs.appcelerator.com/platform/latest/#!/api/Modules.Facebook","bubbles":true,"type":"login","source":{},"cancelBubble":false}`

I added more information in the ticket : https://jira.appcelerator.org/browse/AC-5756

Thanks, and best,
Antonio.

**Comment by hansemannn** [comment]
This has nothing to do with this pull request. You are having issues with your entitlements, please reach out for the community in that case.

**Comment by antonioduran** [comment]
Hello @hansemannn . 

Even adding the entitlements is happening this situation, that's why added more details on the old ticket that it was reported before, but thank you - I will do a double check again..

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>keychain-access-groups</key>
    <array>
        <string>$(AppIdentifierPrefix)<application id></string>
    </array>
</dict>
</plist>
```
platform/ios/name.entitlement

**name** same as it is in the tiapp.xml
test
**application id**  same as it is in the tiapp.xml
com.test.test
Thanks, and best,
Antonio.

**Review by janvennemann — APPROVED** [review]

**Comment by janvennemann** [comment]
holding off merging for now until release schedule with SDK is clarified due to breaking changes

@antonioduran please stop using this PR for unrelated support requests. As Hans said reach out to the community e.g. on slack or open a ticket if you think this is a bug. // Edit: Ah i see the ticket now. Thanks!

**Comment by hansemannn** [comment]
Thanks Jan! Quick note: If SDK 8 does not take this version, merging this will not influence that behavior until the `modules.json` is updated with the release binary link. See the recent Ti.Map changes that are also merged already, for the early bird OSS devs. 😇

**Comment by janvennemann** [comment]
@hansemannn Yes, i know. I was just thinking about branching master before that so we would have branch for potential fixes of the old versions before breaking changes. There is also an ongoing discussion wether breaking changes in shipped modules should only be introduced in major SDK updates.

I guess i'll just branch off of master and then we can see when to update the shipped module ;)

**Pull request merged**
