### PR TITLE
feat(ios): update to Facebook SDK 13.1.0, support Apple Silicon / macOS, remove deprecated game request

### PR DESCRIPTION
**Pull request by hansemannn**
For Android, see: #282

### CODE REVIEW

**Comment by kosso** [comment]
Any reason why this has not been merged yet? 

It's currently impossible to test apps on an M1 Mac Simulator while using ti.facebook.

**Comment by hansemannn** [comment]
@kosso The merging was blocked due to the TiDev migration. All open pull reviews in all module repos will be reviewed and merged or closed over the next few weeks. But you can use it already of course!

**Comment by kosso** [comment]
Hi Hans.  Thanks for the update and info.

Is there any chance you could share the built module zips?  I'm having
trouble building them here. on my new M1.

Many thanks!

**Comment by hansemannn** [comment]
https://www.dropbox.com/s/mal5foazx3xlw4u/facebook-iphone-12.0.0.zip?dl=1 Have fun!

**Comment by hansemannn** [comment]
@m1ga Now using the latest version from last week. @kosso Would you mind testing it out as well? I think we are pretty up-to-date again now :)

**Comment by m1ga** [comment]
I've pushed the Android version to 13.1.0 too! Man, they release updates every month :rofl:

**Pull request merged**
