### PR TITLE
[MOD-2318] iOS: Update FB-SDK to 4.18.0, fix docs, add new methods

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA**: https://jira.appcelerator.org/browse/MOD-2318

### CODE REVIEW

**Review by vijaysingh-axway — COMMENTED** [review]
When trying to setCurrentAccessToken using -
fb.setCurrentAccessToken({
			appID:'1347939349301',
			permissions:['public_profile','email','gender'],
	});
Ti.API.info(fb.appID);  //  Is not printing the value as set in above function
Ti.API.info(fb.permissions); // Is printing the value as set in above function

I think there should be an example to use setCurrentAccessToken() function in our doc.

**Comment by hansemannn** [comment]
It should already be documented [here](https://github.com/appcelerator-modules/ti.facebook/pull/80/files#diff-5723ce12442d8a4e7043b84fa4c4ffacR880) and [here](https://github.com/appcelerator-modules/ti.facebook/pull/80/files#diff-5723ce12442d8a4e7043b84fa4c4ffacR2101). It will be generated / expanded to the web-docs [here](http://docs.appcelerator.com/platform/latest/#!/api/Modules.Facebook). 

I will check if it's our issue or an FB-SDK issue. Anyway, I will add an code example to the docs as well. 

**EDIT**: But reported in [#675847029242342](https://developers.facebook.com/bugs/675847029242342)

**Comment by hansemannn** [comment]
The FB docs also state "Refresh the current access token's permission state and extend the token's expiration date, if possible.", so I guess the FB SDK will decide whether or not to change the values or not. This is not really a clear statement, but all we have. Anyway, it doesn't like a ti.facebook issue to me.

**Review by vijaysingh-axway — APPROVED** [review]
FT and CR passed.

**Pull request merged**
