### PR TITLE
feat(ios): support Facebook SDK 6.0.0

### PR DESCRIPTION
**Pull request by hansemannn**
Removing all `FBSDKPlacesKit` related API's as well as the `shareToMessanger` method and `loginBehavior` related API's.

https://jira.appcelerator.org/browse/MOD-2597

### CODE REVIEW

**Comment by vijaysingh-axway** [comment]
@hansemannn  Thanks for PR!. Can you resolve conflict and linting issues please.

**Comment by vijaysingh-axway** [comment]
@sgtcoolguy Can you please look in build failure? It looks while running for iOS unit test,  it is failing.

**Comment by sgtcoolguy** [comment]
The build is failing on iOS:
```
  Undefined symbols for architecture x86_64:
    "_vDSP_mmul", referenced from:
        mat1::dense(float*, float*, float*, int, int, int) in FBSDKCoreKit(FBSDKEventInferencer.o)
        mat1::dense(float*, float*, float*, int, int, int) in FBSDKCoreKit(FBSDKAddressInferencer.o)
    "_vDSP_dotpr", referenced from:
        mat1::conv1D(float*, float*, int, int, int, int, int) in FBSDKCoreKit(FBSDKEventInferencer.o)
        mat1::conv1D(float*, float*, int, int, int, int, int) in FBSDKCoreKit(FBSDKAddressInferencer.o)
    "_vDSP_vclip", referenced from:
        +[FBSDKEventInferencer predict:viewTree:withLog:] in FBSDKCoreKit(FBSDKEventInferencer.o)
        +[FBSDKAddressInferencer shouldFilterParam:] in FBSDKCoreKit(FBSDKAddressInferencer.o)
  ld: symbol(s) not found for architecture x86_64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  ** BUILD FAILED **
  The following build commands failed:
  	Ld /var/folders/50/qx040w2x4nl3p6zsl5zkp7th0000gp/T/karma-74948884/facebook.karmarunner/build/iphone/build/Products/Debug-iphonesimulator/facebook.karmarunner.app/facebook.karmarunner normal x86_64
  (1 failure)
```

**Comment by hansemannn** [comment]
Looks like a missing `-framework Accelerate` flag in the module.xcconfig. Facebook probably forgot to link it? We use the above version in production since last month, but likely link it with another framework already.

**Comment by sgtcoolguy** [comment]
Need to bump the package.json version major to match the bump done in iOS:
```
npm --no-git-tag-version version major
```

**Review by vijaysingh-axway — APPROVED** [review]
Changes looks good.

**Comment by brentonhouse** [comment]
@sgtcoolguy  - Is this good to merge now?

**Pull request merged**
