### PR TITLE
[MOD-2241] Support "statuschange" event on LikeButton

### PR DESCRIPTION
**Pull request by hansemannn**
JIRA: https://jira.appcelerator.org/browse/MOD-2241

### CODE REVIEW

**Comment by hansemannn** [comment]
**EDIT** Looks like his facebook app configuration was incorrect, he will take a look! 🚀 

@andreasanta, the Android builds throws the following error (detected by @AngelkPetkov):

```
[ERROR] :  TiBaseActivity: (main) [0,1] Error dispatching lifecycle event: Both context and applicationId must be non-null
[ERROR] :  TiBaseActivity: java.lang.IllegalArgumentException: Both context and applicationId must be non-null
[ERROR] :  TiBaseActivity:     at com.facebook.appevents.AppEventsLogger.activateApp(AppEventsLogger.java:281)
[ERROR] :  TiBaseActivity:     at com.facebook.appevents.AppEventsLogger.activateApp(AppEventsLogger.java:268)
[ERROR] :  TiBaseActivity:     at facebook.TiFacebookModule.onResume(TiFacebookModule.java:130)
[ERROR] :  TiBaseActivity:     at org.appcelerator.titanium.TiLifecycle.fireLifecycleEvent(TiLifecycle.java:150)
[ERROR] :  TiBaseActivity:     at org.appcelerator.titanium.TiBaseActivity.onResume(TiBaseActivity.java:1308)
[ERROR] :  TiBaseActivity:     at org.appcelerator.titanium.TiLaunchActivity.onResume(TiLaunchActivity.java:389)
[ERROR] :  TiBaseActivity:     at org.appcelerator.titanium.TiRootActivity.onResume(TiRootActivity.java:114)
[ERROR] :  TiBaseActivity:     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1258)
[ERROR] :  TiBaseActivity:     at android.app.Activity.performResume(Activity.java:6327)
[ERROR] :  TiBaseActivity:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
[ERROR] :  TiBaseActivity:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
[ERROR] :  TiBaseActivity:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
[ERROR] :  TiBaseActivity:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
[ERROR] :  TiBaseActivity:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
[ERROR] :  TiBaseActivity:     at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] :  TiBaseActivity:     at android.os.Looper.loop(Looper.java:148)
[ERROR] :  TiBaseActivity:     at android.app.ActivityThread.main(ActivityThread.java:5417)
[ERROR] :  TiBaseActivity:     at java.lang.reflect.Method.invoke(Native Method)
[INFO] :   ity:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
[ERROR] :  TiBaseActivity:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
[ERROR] :  TiBaseActivity: (main) [0,64] Error dispatching lifecycle event: Both context and applicationId must be non-null
[ERROR] :  TiBaseActivity: java.lang.IllegalArgumentException: Both context and applicationId must be non-null
[ERROR] :  TiBaseActivity:     at com.facebook.appevents.AppEventsLogger.deactivateApp(AppEventsLogger.java:335)
[ERROR] :  TiBaseActivity:     at com.facebook.appevents.AppEventsLogger.deactivateApp(AppEventsLogger.java:322)
[ERROR] :  TiBaseActivity:     at facebook.TiFacebookModule.onPause(TiFacebookModule.java:137)
[ERROR] :  TiBaseActivity:     at org.appcelerator.titanium.TiLifecycle.fireLifecycleEvent(TiLifecycle.java:151)
[ERROR] :  TiBaseActivity:     at org.appcelerator.titanium.TiBaseActivity.onPause(TiBaseActivity.java:1254)
[ERROR] :  TiBaseActivity:     at org.appcelerator.titanium.TiLaunchActivity.onPause(TiLaunchActivity.java:337)
[ERROR] :  TiBaseActivity:     at android.app.Activity.performPause(Activity.java:6363)
[ERROR] :  TiBaseActivity:     at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1311)
[ERROR] :  TiBaseActivity:     at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3367)
[ERROR] :  TiBaseActivity:     at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3340)
[ERROR] :  TiBaseActivity:     at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3315)
[ERROR] :  TiBaseActivity:     at android.app.ActivityThread.-wrap13(ActivityThread.java)
[ERROR] :  TiBaseActivity:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
[ERROR] :  TiBaseActivity:     at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] :  TiBaseActivity:     at android.os.Looper.loop(Looper.java:148)
[ERROR] :  TiBaseActivity:     at android.app.ActivityThread.main(ActivityThread.java:5417)
[ERROR] :  TiBaseActivity:     at java.lang.reflect.Method.invoke(Native Method)
[ERROR] :  TiBaseActivity:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
[ERROR] :  TiBaseActivity:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by hansemannn** [comment]
@andreasanta Can you check that again, please?

**Comment by ashcoding** [comment]
I will be checking this.

**Comment by hansemannn** [comment]
@andreasanta Last ping, will you be able to check the issues? Otherwise we will close this PR as non-resolved. But I personally really want this in, thank you!

**Pull request closed without merging**
