### PR TITLE
[ios/android] Fire event when like status changes

### PR DESCRIPTION
**Pull request by andreasanta**
Allows to detect when the like status of the native like button
changes, by firing the “statuschanged” event.

### CODE REVIEW

**Comment by andreasanta** [comment]
Just signed the CLA, sorry didn't know about it.

**Comment by hansemannn** [comment]
@cheekiatng Is this covered in your latest PR?

**Comment by cheekiatng** [comment]
nope.

**Comment by andreasanta** [comment]
We've also developed an Android version if you would like I can submit that as well.

**Comment by ashcoding** [comment]
@andreasanta Yes please. All PRs are most welcomed.

Bonus points if they have:-
-Documentation
-Testing steps
-Jira Ticket

**Comment by andreasanta** [comment]
Of course, will try and do that this week. Thank you guys.

**Comment by hansemannn** [comment]
@andreasanta: Thank you! Please make sure you commit against the latest iOS and Android versions, since we had some major releases lately. As soon as the PR is ready, we will review!

**Comment by hansemannn** [comment]
Hi @andreasanta, did you find the time to check the android version, yet? We would support you by writing the docs and setup a JIRA ticket for you.

**Comment by andreasanta** [comment]
Hi @hansemannn, sorry for the late reply, it's been a busy week trying to get some OpenWRT router to work.

Just merged upstream changes and added Android code. Basically, the code triggers the "status changed" event, with an empty object, whenever the like button status changes from liked to unliked or viceversa.

There is currently no way of passing the like status through the event, but the user might invoke Facebook APIs again to check the new status.

I really hope this helps!

**Comment by hansemannn** [comment]
To get this rolling a bit, my code review feedback:
- Remove debug logs
- Name the event "statuschange" to conform with other event naming conventions
- Check if the event listener is set (e.g. iOS: `if ([[self proxy] _hasListeners:@"statuschange"])`)
- Document the new event in the apidocs
- Make sure the indentation is correct (see [here](https://github.com/appcelerator-modules/ti.facebook/pull/27/files#diff-e7ba8f4cf97191e38113c27443c04407R89))
- Make sure travis CI does not fail (see [here](https://travis-ci.org/appcelerator-modules/ti.facebook/builds/92669384#L1449))

Also, I would wait for @ashcoding to give  me a :+1: for the Android part. Thanks!

**Comment by hansemannn** [comment]
@andreasanta Are you still planning to update the suggested changes? We would greatly appreciate that! If you have further questions on certain things, feel free to ask me!

**Comment by hansemannn** [comment]
The CLA is signed. We will try to adapt your changes by cherry-picking and fixing the outstanding issues.

**Comment by andreasanta** [comment]
@hansemannn I'm sorry I'm overwhelmed at work. When would you need this to be completed so it gets into the next release?

**Comment by hansemannn** [comment]
By next week, so we are able to test it properly.

**Comment by hansemannn** [comment]
Closing in favor if https://github.com/appcelerator-modules/ti.facebook/pull/47

**Pull request closed without merging**
