### PR TITLE
Mac support

### PR DESCRIPTION
**Pull request by sgtcoolguy**
**JIRA**: https://jira.appcelerator.org/browse/TIMOB-28124

**Description**
- Builds with the latest 9_2_X SDK build so that macOS support is not compiled
- Updates iOS to Facebook iOS SDK 7.1.1 (from 6.0.0)
- Updates Android to Facebook Android SDK 7.1.0 (from 5.13.0)
- Bumps module versions/npm package versions to reflect major revs of Facebook sdk

### CODE REVIEW

**Comment by sgtcoolguy** [comment]
Note that this breaks when we "archive" for macOS due to the underlying frameworks not supporting macOS.

**Comment by sgtcoolguy** [comment]
Note that #127 doesn't "fix" the macOS support either. So we need to either find a way so native module can explicitly exclude macOS support - or we need to see if we can rebuild the FB frameworks from source with macOS support?

**Comment by vijaysingh-axway** [comment]
@sgtcoolguy  I think -
1. While building module, make mac build optional. If build get failed for mac, just log message and proceed to create xcframework with device and simulator build.
2. Most of the third party frameworks are not supporting simulator 'arm64' yet. So building modules with third party framework will also fail with Xcode 12. As only way to support simulator 'arm64' is to create XCFramework, so in any module if platform folder has  ".framework" file, exclude simulator 'arm64' and build.

**Comment by hansemannn** [comment]
See https://github.com/facebook/facebook-ios-sdk/issues/1381 for the macOS target at Facebook. I don't think this needs to be merged until Facebook isn't ready.

**Review by vijaysingh-axway — APPROVED** [review]
CR passed.

**Pull request merged**
