### PR TITLE
Add more parameters for logCustomEvent function

### PR DESCRIPTION
**Pull request by danghy**
Allow to add **valueToSum** and your own **parameters** to custom events
Example:

``` javascript
facebook.logCustomEvent('Login');
facebook.logCustomEvent('Login', 54.23);
facebook.logCustomEvent('Login', 54.23, {"LoginID": "8866600", "LoginType": "facebook"});
```

screen shot 2015-08-17 at 4 19 55 pm

### CODE REVIEW

**Comment by ashcoding** [comment]
Thanks @danghy! I'll try to take a look at this as soon as humanly possible. If I don't, please nudge me. :+1:

**Comment by hansemannn** [comment]
@ashcoding: iOS side looks good, can you check Android? Also, we will need doc updates for the new params.

**Comment by ashcoding** [comment]
@hansemannn Android sides looks okay. As you mentioned, need docs and rebasing cause Facebook module has just been updated to use the latest sdk.

**Comment by hansemannn** [comment]
Hey @danghy, we still would welcome your changes. Over the time, the Facebook SDK has already been updated. So can you please open a new PR based on the latest code base and include docs so people know how to use it.

P.S.: Please open a JIRA-ticket as soon as your PR is ready and ping me so we can continue reviewing. The JIRA-ticket is necessary to being tested by our QE. Thank you!

**Pull request closed without merging**
