### PR TITLE
Document and Readme Updates.

### PR DESCRIPTION
**Pull request by ashcoding**

### CODE REVIEW

**Comment by ashcoding** [comment]
@pec1985 Please review. Thank you!

**Comment by pec1985** [comment]
Validation of the documentation fails with a bunch of errors:

```
Modules.Facebook: found 9 error(s)!
    description
        String contains non-ASCII characters.
    extends
        Not a valid class: Titanium.Module
    methods
        initialize
            parameters
                timeout
                    type
                        int
        presentShareDialog
            parameters
                params
                    Invalid key: description
        presentWebShareDialog
            parameters
                params
                    Invalid key: description
        presentSendRequestDialog
            parameters
                params
                    Invalid key: description
        requestWithGraphPath
            parameters
                params
                    Invalid key: description
        requestNewReadPermissions
            parameters
                audience
                    type
                        int
        requestNewPublishPermissions
            parameters
                audience
                    type
                        int

[ERROR] /Users/penrique/Documents/github/modules/ti.facebook/apidoc/Facebook.yml
FacebookGraphResponse: found 1 error(s)!
    extends
        Not a valid class: ErrorResponse

[ERROR] /Users/penrique/Documents/github/modules/ti.facebook/apidoc/Facebook.yml
FacebookPermissionResponse: found 1 error(s)!
    extends
        Not a valid class: ErrorResponse

[ERROR] /Users/penrique/Documents/github/modules/ti.facebook/apidoc/LikeButton.yml
Modules.Facebook.LikeButton: found 1 error(s)!
    description
        String contains non-ASCII characters.

[ERROR] /Users/penrique/Documents/github/modules/ti.facebook/apidoc/LoginButton.yml
Modules.Facebook.LoginButton: found 1 error(s)!
    extends
        Not a valid class: Titanium.UI.View

[ERROR] Found 13 error(s)!
```

**NOTE** You can ignore anything that says "Not a valid class"
- Replace `type: int` with `type: Number`
- In Sublime Text, do a regex search for `[^\x00-\x7F]` to find non-ASCII characters
- Inside of `parameters`, remove the property `description` and just leave it as `summary`
- To create a new paragraph, leave an empty line

To test, clone `titanium_mobile` and
- $ cd to titanium_mobile /apidoc
- $ node validate path_to_this_module/apidoc

**Comment by ashcoding** [comment]
Thank you for the clear instructions.

Fixed validation errors. Please review. Thank you.

**Comment by cheekiatng** [comment]
FR pass. Merging.

**Pull request merged**
