### PR TITLE
[TIMOB-23521] iOS/Android: Support "mode" in presentShareDialog

### PR DESCRIPTION
**Pull request by hansemannn**
JIRA: https://jira.appcelerator.org/browse/TIMOB-23521

### CODE REVIEW

**Comment by hansemannn** [comment]
@ashcoding  Android keeps failing because "mode" is not known. I have no idea why, the used 4.12.0 version should be new enough.

**Comment by ashcoding** [comment]
Sounds like I'll need to check this out.

**Comment by ashcoding** [comment]
Your Android code has a slight error. The `mode` variable is not in the correct code block/not in scope. Did a PR to your PR. https://github.com/hansemannn/ti.facebook/pull/1

**Comment by ashcoding** [comment]
PR is now passing.

**Pull request merged**
